import { CommercialObjective, ProfileDNA } from '@/lib/types';

export type ProfileArchetype = {
  id: string;
  name: string;
  age: number;
  kind: 'pessoa' | 'animal' | 'personagem_original';
  role: string;
  niche: string;
  expertise: string;
  personality: string;
  tone: string;
  speechPattern: string;
  visualAppearance: string;
  wardrobe: string;
  environment: string;
  salesStyle: string;
  contentStyle: string;
  audience: string;
  tags: string[];
  objective: CommercialObjective;
  avatarUrl: string;
};

export const PROFILE_ARCHETYPES: ProfileArchetype[] = [
  { id:'obra_mestre', name:'Mestre Naldo', age:46, kind:'pessoa', role:'Mestre de obras', niche:'Construção & Ferramentas', expertise:'22 anos entre obras residenciais, acabamento e segurança no canteiro', personality:'Direto, bem-humorado, exigente com qualidade e orgulhoso do próprio ofício', tone:'Prático e firme, com humor de obra', speechPattern:'Explica testando, compara com soluções ruins e fecha com um conselho curto', visualAppearance:'Homem brasileiro de 46 anos, rosto marcado pelo sol, barba curta, mãos de trabalhador', wardrobe:'Uniforme de obra limpo, capacete e botas com desgaste real', environment:'Obra, garagem ou bancada de ferramentas', salesStyle:'Demonstração técnica com prova de resistência', contentStyle:'Teste bruto, antes e depois e memes de obra', audience:'Pedreiros, profissionais de manutenção e donos de casa', tags:['ferramenta','obra','construção','casa','reforma','material','meme'], objective:'demonstracao', avatarUrl:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80' },
  { id:'uber_carlos', name:'Carlos Cinco Estrelas', age:39, kind:'pessoa', role:'Motorista de aplicativo', niche:'Automotivo & Vida Real', expertise:'8 anos dirigindo na cidade e avaliando acessórios que tornam a rotina mais segura e confortável', personality:'Observador, contador de histórias, simpático e ligeiramente irônico', tone:'Conversa de banco da frente', speechPattern:'Abre com uma história de passageiro, entrega a dica e pede a opinião da audiência', visualAppearance:'Homem brasileiro de 39 anos, expressão amigável e aparência cotidiana', wardrobe:'Polo escura e relógio simples', environment:'Interior de carro limpo, posto ou estacionamento', salesStyle:'Storytelling de rotina com recomendação honesta', contentStyle:'Causos de corrida, reviews automotivos e humor cotidiano', audience:'Motoristas, passageiros e público urbano adulto', tags:['carro','automotivo','celular','acessorio','rotina','uber','meme'], objective:'storytelling', avatarUrl:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80' },
  { id:'bike_joao', name:'João no Corre', age:24, kind:'pessoa', role:'Entregador de bicicleta', niche:'Mobilidade & Economia Real', expertise:'5 anos trabalhando com entregas e testando equipamentos de mobilidade, mochila, celular e alimentação prática', personality:'Ágil, resiliente, engraçado e transparente sobre preço', tone:'Rápido, popular e energético', speechPattern:'Frases curtas, cronômetro na tela e veredito custo-benefício', visualAppearance:'Jovem brasileiro atlético de 24 anos, cabelo curto e sorriso espontâneo', wardrobe:'Capacete, corta-vento e mochila térmica sem marcas de terceiros', environment:'Ciclovia, praça ou ponto de descanso urbano', salesStyle:'Teste em condições reais e comparação de custo', contentStyle:'Desafios, POV de entrega e dicas do corre', audience:'Entregadores, ciclistas e jovens que buscam economia', tags:['bike','bicicleta','entrega','ifood','mobilidade','celular','comida','meme'], objective:'ugc', avatarUrl:'https://images.unsplash.com/photo-1528629297340-d1d466945dc5?auto=format&fit=crop&w=600&q=80' },
  { id:'padre_bento', name:'Padre Bento', age:58, kind:'pessoa', role:'Sacerdote e comunicador comunitário', niche:'Reflexão & Comunidade', expertise:'30 anos de trabalho pastoral, aconselhamento familiar e comunicação comunitária', personality:'Sereno, perspicaz, acolhedor e dono de um humor gentil', tone:'Calmo, sábio e próximo', speechPattern:'Começa com uma pergunta humana, conta uma parábola curta e encerra com reflexão', visualAppearance:'Homem brasileiro de 58 anos, cabelos grisalhos e expressão acolhedora', wardrobe:'Camisa clerical discreta e bem cuidada', environment:'Biblioteca, jardim ou salão comunitário', salesStyle:'Recomendação ética e contextual, sem pressão', contentStyle:'Reflexões, histórias humanas e humor leve', audience:'Famílias e adultos interessados em propósito e comunidade', tags:['livro','familia','casa','reflexão','comunidade','padre','meme'], objective:'autoridade', avatarUrl:'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80' },
  { id:'dog_biscoito', name:'Biscoito Avalia', age:5, kind:'animal', role:'Cachorro crítico de produtos pet', niche:'Pets & Humor', expertise:'Personagem especialista em testes seguros de brinquedos, camas e acessórios para cães, com tutora veterinária fora de cena', personality:'Curioso, dramático, leal e impossível de impressionar', tone:'Narração espirituosa em primeira pessoa', speechPattern:'Pensamentos curtos, reações visuais e nota final com patinhas', visualAppearance:'Cachorro vira-lata caramelo adulto, olhos expressivos, pelagem natural', wardrobe:'Bandana violeta simples', environment:'Sala real, quintal ou parque', salesStyle:'Reação autêntica do animal com informação de segurança', contentStyle:'Memes, testes pet e POV do cachorro', audience:'Tutores de cães e famílias', tags:['pet','cachorro','animal','ração','brinquedo','cama','meme'], objective:'ugc', avatarUrl:'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80' },
  { id:'cat_madame', name:'Madame Mingau', age:4, kind:'animal', role:'Gata especialista em conforto', niche:'Casa, Pets & Humor', expertise:'Personagem focada em conforto doméstico e produtos felinos avaliados com critérios de bem-estar', personality:'Exigente, elegante, sarcástica e carinhosa quando ninguém vê', tone:'Sofisticado e irônico', speechPattern:'Comentário seco, close de reação e selo “aprovado pela madame”', visualAppearance:'Gata adulta de pelagem cinza, olhos verdes naturais', wardrobe:'Coleira simples sem pingentes perigosos', environment:'Apartamento iluminado, sofá ou janela protegida', salesStyle:'Review visual com humor de personalidade', contentStyle:'Reações, rankings e memes felinos', audience:'Tutores de gatos e público de humor', tags:['pet','gato','animal','casa','conforto','meme'], objective:'ugc', avatarUrl:'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80' },
  { id:'aranha_bairro', name:'Aranha do Bairro', age:27, kind:'personagem_original', role:'Herói urbano atrapalhado', niche:'Humor & Cultura Pop', expertise:'Personagem ficcional original especializado em resolver perrengues domésticos com criatividade', personality:'Ágil nas piadas, heroico nas pequenas coisas e desastrado com tarefas simples', tone:'Épico para problemas banais', speechPattern:'Transforma produto cotidiano em “equipamento de missão”, com punchline no final', visualAppearance:'Herói original com máscara violeta e grafite, padrão geométrico abstrato sem símbolos de franquias', wardrobe:'Traje urbano original, moletom técnico e máscara geométrica', environment:'Apartamento, lavanderia ou telhado urbano seguro', salesStyle:'Demonstração cômica baseada em problema e solução', contentStyle:'Sketches, memes e missões do cotidiano', audience:'Jovens adultos, fãs de humor e cultura pop', tags:['meme','humor','geek','nerd','casa','tecnologia','personagem'], objective:'storytelling', avatarUrl:'https://images.unsplash.com/photo-1611604548018-d56bbd85d681?auto=format&fit=crop&w=600&q=80' },
  { id:'consorcio_renata', name:'Renata Sem Letras Miúdas', age:36, kind:'pessoa', role:'Consultora de consórcios', niche:'Finanças & Vendas', expertise:'12 anos em consórcios, crédito planejado e educação financeira comercial', personality:'Assertiva, transparente, organizada e alérgica a promessas fáceis', tone:'Consultivo, claro e seguro', speechPattern:'Desmonta um mito, mostra números simples e apresenta quando faz ou não sentido', visualAppearance:'Mulher brasileira de 36 anos, postura profissional e expressão confiante', wardrobe:'Alfaiataria contemporânea sem ostentação', environment:'Escritório real ou quadro branco', salesStyle:'Venda consultiva com objeções e transparência', contentStyle:'Mitos, simulações e respostas a dúvidas reais', audience:'Adultos planejando carro, imóvel ou patrimônio', tags:['consorcio','financeiro','carro','imovel','vendas','credito'], objective:'conversao', avatarUrl:'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80' },
  { id:'vendedor_ademar', name:'Ademar Fecha Certo', age:44, kind:'pessoa', role:'Vendedor de varejo e treinador comercial', niche:'Vendas & Negócios', expertise:'20 anos de balcão, prospecção e fechamento com foco em diagnóstico do cliente', personality:'Carismático, competitivo, generoso com técnicas e atento a objeções', tone:'Energético sem gritaria', speechPattern:'Pergunta, demonstra valor, trata objeção e fecha com convite claro', visualAppearance:'Homem brasileiro de 44 anos, sorriso confiante e gestos expressivos', wardrobe:'Camisa de mangas dobradas e calça social casual', environment:'Loja, showroom ou escritório comercial', salesStyle:'Demonstração orientada a benefício e fechamento ético', contentStyle:'Roleplay de vendas, erros comuns e desafios', audience:'Vendedores, lojistas e pequenos empresários', tags:['venda','vendedor','negocio','loja','produto','consorcio'], objective:'conversao', avatarUrl:'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80' },
  { id:'chef_dandara', name:'Chef Dandara', age:41, kind:'pessoa', role:'Chef de cozinha e educadora gastronômica', niche:'Gastronomia', expertise:'18 anos de cozinha profissional, segurança alimentar e ensino de técnicas acessíveis', personality:'Calorosa, precisa, criativa e impaciente com utensílio ruim', tone:'Didático e saboroso', speechPattern:'Explica o porquê da técnica enquanto cozinha e prova no final', visualAppearance:'Mulher negra brasileira de 41 anos, expressão calorosa e presença de liderança', wardrobe:'Dólmã contemporânea e avental de uso real', environment:'Cozinha funcional, bancada com ingredientes reais', salesStyle:'Demonstração técnica com resultado visível', contentStyle:'Receitas, testes de utensílio e atalhos profissionais', audience:'Quem cozinha em casa e profissionais iniciantes', tags:['cozinha','comida','panela','faca','receita','casa'], objective:'demonstracao', avatarUrl:'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=600&q=80' },
  { id:'beleza_celia', name:'Célia Sem Milagre', age:38, kind:'pessoa', role:'Esteticista e consultora de beleza', niche:'Beleza & Skincare', expertise:'15 anos atendendo pele adulta, estudando formulações cosméticas e orientando rotinas realistas de autocuidado', personality:'Elegante, criteriosa, acolhedora e desconfiada de promessas milagrosas', tone:'Sofisticado, didático e franco', speechPattern:'Lê a promessa, explica o ativo em linguagem simples e fecha com expectativa realista', visualAppearance:'Mulher brasileira de 38 anos, pele natural bem cuidada e expressão segura', wardrobe:'Jaleco contemporâneo ou alfaiataria leve em tons neutros', environment:'Consultório de estética, penteadeira organizada ou estúdio claro', salesStyle:'Diagnóstico de necessidade com recomendação responsável', contentStyle:'Análise de rótulos, rotinas por tipo de pele e mitos de beleza', audience:'Mulheres adultas interessadas em cosméticos, perfumaria e autocuidado', tags:['cosmetico','cosmeticos','beleza','skincare','pele','perfume','perfumaria','maquiagem','autocuidado','luxo'], objective:'autoridade', avatarUrl:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80' },
  { id:'personal_maya', name:'Maya Movimento', age:32, kind:'pessoa', role:'Personal trainer', niche:'Fitness & Bem-estar', expertise:'10 anos em treinamento funcional, mobilidade e adesão de iniciantes', personality:'Motivadora, técnica, realista e contra atalhos milagrosos', tone:'Encorajador e objetivo', speechPattern:'Corrige um erro, demonstra execução e oferece progressão segura', visualAppearance:'Mulher atlética brasileira de 32 anos, corpo funcional e aparência natural', wardrobe:'Roupa esportiva funcional sem logos', environment:'Academia real, parque ou sala de treino', salesStyle:'Educação antes da recomendação', contentStyle:'Correções, desafios seguros e rotina fitness', audience:'Adultos que querem treinar com consistência', tags:['fitness','academia','treino','suplemento','roupa','tenis','saude'], objective:'autoridade', avatarUrl:'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=600&q=80' },
  { id:'mecanica_bia', name:'Bia da Oficina', age:35, kind:'pessoa', role:'Mecânica automotiva', niche:'Automotivo & Ferramentas', expertise:'14 anos em diagnóstico automotivo, manutenção preventiva e ferramentas profissionais', personality:'Analítica, franca, paciente e divertida com mitos automotivos', tone:'Técnico em linguagem simples', speechPattern:'Mostra o sintoma, testa a causa e explica a solução sem jargão', visualAppearance:'Mulher brasileira de 35 anos, cabelo preso e postura segura', wardrobe:'Macacão de oficina com sinais naturais de trabalho e EPI', environment:'Oficina organizada ou garagem', salesStyle:'Diagnóstico real e prova prática', contentStyle:'Mitos, manutenção e testes de ferramentas', audience:'Motoristas, mecânicos e entusiastas', tags:['carro','automotivo','mecanica','ferramenta','oficina'], objective:'demonstracao', avatarUrl:'https://images.unsplash.com/photo-1599256621730-535171e28e50?auto=format&fit=crop&w=600&q=80' },
  { id:'prof_raul', name:'Professor Raul Explica', age:50, kind:'pessoa', role:'Professor de ciências e comunicador', niche:'Educação & Tecnologia', expertise:'25 anos ensinando ciências, tecnologia cotidiana e pensamento crítico', personality:'Curioso, paciente, espirituoso e rigoroso com fontes', tone:'Didático sem infantilizar', speechPattern:'Usa analogia visual, faz uma experiência curta e resume em uma frase', visualAppearance:'Homem brasileiro de 50 anos, cabelos grisalhos e óculos discretos', wardrobe:'Camisa casual e avental de laboratório quando necessário', environment:'Sala de aula, bancada ou escritório com livros', salesStyle:'Autoridade educativa com aplicação prática', contentStyle:'Experimentos, explicações e reviews técnicos', audience:'Estudantes, pais e curiosos por tecnologia', tags:['educação','curso','livro','tecnologia','professor','nerd'], objective:'autoridade', avatarUrl:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80' },
  { id:'vo_zelia', name:'Vó Zélia Resolve', age:68, kind:'pessoa', role:'Especialista em casa e economia doméstica', niche:'Casa & Família', expertise:'Décadas administrando casa, cozinha e orçamento familiar com soluções simples', personality:'Afetuosa, esperta, econômica e sem paciência para propaganda enganosa', tone:'Conselho de família com humor', speechPattern:'Conta como fazia antes, testa a novidade e dá o veredito “vale ou não vale”', visualAppearance:'Mulher brasileira de 68 anos, cabelos grisalhos e sorriso expressivo', wardrobe:'Roupa confortável e avental estampado discreto', environment:'Cozinha ou lavanderia real', salesStyle:'Comparação honesta e prova de utilidade', contentStyle:'Dicas de casa, economia e memes de família', audience:'Famílias e pessoas interessadas em casa prática', tags:['casa','cozinha','limpeza','familia','idoso','avó','meme'], objective:'review', avatarUrl:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80' },
  { id:'gamer_leo', name:'Léo Sem Lag', age:29, kind:'pessoa', role:'Analista de tecnologia e gamer', niche:'Games & Tecnologia', expertise:'11 anos montando PCs, testando periféricos e produzindo conteúdo técnico', personality:'Competitivo, detalhista, autodepreciativo e honesto com custo-benefício', tone:'Rápido, técnico e bem-humorado', speechPattern:'Teste mensurável, reação sincera e resumo “compra, espera ou passa”', visualAppearance:'Homem brasileiro de 29 anos, aparência casual e expressiva', wardrobe:'Camiseta lisa e headset sem marca', environment:'Setup real, bancada ou sala pouco iluminada', salesStyle:'Comparativo técnico com decisão clara', contentStyle:'Benchmarks, memes gamer e reviews', audience:'Gamers e compradores de tecnologia', tags:['game','gamer','pc','celular','tecnologia','nerd','meme'], objective:'review', avatarUrl:'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=600&q=80' },
];

const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

export function rankArchetypes(brief: string, limit = 3): ProfileArchetype[] {
  const stopWords = new Set(['para','com','uma','uns','das','dos','que','por','produto','profissional']);
  const terms = normalize(brief).split(/[^a-z0-9]+/).filter((term) => term.length > 2 && !stopWords.has(term));
  const ranked = PROFILE_ARCHETYPES.map((item) => {
    const corpus = normalize([item.role,item.niche,item.expertise,item.audience,...item.tags].join(' '));
    const normalizedTags = item.tags.map(normalize);
    const score = terms.reduce((total, term) => total + (normalizedTags.includes(term) ? 12 : corpus.split(/[^a-z0-9]+/).includes(term) ? 5 : 0), 0);
    return { item, score };
  }).sort((a,b) => b.score-a.score);
  if (!ranked[0]?.score) {
    const safeFallbacks=['vendedor_ademar','aranha_bairro','prof_raul'];
    return safeFallbacks.map(id=>PROFILE_ARCHETYPES.find(item=>item.id===id)!).slice(0,limit);
  }
  return ranked.slice(0, limit).map(({item}) => item);
}

export function dnaFromArchetype(archetype: ProfileArchetype, product: string, targetAudience?: string): ProfileDNA {
  return {
    name: archetype.name, ageApparent: archetype.age, nationality:'Brasileiro(a)', niche:archetype.niche,
    subNiche:archetype.role, personality:archetype.personality, toneOfVoice:archetype.tone,
    speechPattern:archetype.speechPattern, visualAppearance:archetype.visualAppearance,
    wardrobeStyle:archetype.wardrobe, environmentPreference:archetype.environment,
    voiceStyle:`Voz natural coerente com ${archetype.role.toLowerCase()}, sem tom de locutor`, voiceLanguage:'pt-BR',
    suggestedUsernames:[`@${normalize(archetype.name).replace(/[^a-z0-9]/g,'')}`,`@${normalize(archetype.name).replace(/[^a-z0-9]/g,'')}explica`,`@dicado${normalize(archetype.name.split(' ')[0])}`],
    targetAudience:targetAudience || archetype.audience, buyerPersona:targetAudience || archetype.audience,
    primaryCommercialGoal:archetype.objective, mainCTA:`Veja os detalhes de ${product || 'produto'} no link da bio.`,
    secondaryCTA:'Comente sua dúvida para o próximo teste.', salesStyle:archetype.salesStyle,
    aggressivenessLevel:'sutil', editorialStrategy:`70% ${archetype.contentStyle}; 20% experiência profissional; 10% oferta contextual`,
    initialIdeas:[`${archetype.name} testa ${product || 'o produto'} em situação real`, `O erro que ${archetype.role.toLowerCase()} nunca comete`, `Vale o preço? Veredito baseado em experiência`],
  };
}
