'use client';

import { useMemo,useState } from 'react';
import { BriefcaseBusiness,CheckCheck,Copy,X } from 'lucide-react';
import { Profile } from '@/lib/types';

export function ProfileProfessionalKitModal({profile,onClose}:{profile:Profile;onClose:()=>void}){
  const [copied,setCopied]=useState(false);
  const kit=useMemo(()=>`KIT PROFISSIONAL — ${profile.name}\n\nPOSICIONAMENTO\n${profile.bio}\nNicho: ${profile.niche}\nPersonalidade: ${profile.personality}\nTom: ${profile.toneOfVoice}\nPadrão de fala: ${profile.dna.speechPattern}\n\nPÚBLICO E VENDA\nPúblico: ${profile.dna.targetAudience}\nPersona: ${profile.dna.buyerPersona}\nObjetivo: ${profile.dna.primaryCommercialGoal}\nEstilo de venda: ${profile.dna.salesStyle}\nCTA principal: ${profile.dna.mainCTA}\nCTA secundário: ${profile.dna.secondaryCTA}\n\nDIREÇÃO VISUAL\nAparência: ${profile.dna.visualAppearance}\nRoupa: ${profile.dna.wardrobeStyle}\nAmbiente: ${profile.dna.environmentPreference}\n\nESTRATÉGIA EDITORIAL\n${profile.dna.editorialStrategy}\n\nIDEIAS INICIAIS\n${profile.dna.initialIdeas.map((idea,index)=>`${index+1}. ${idea}`).join('\n')}\n\nROTEIRO-BASE\nHook: apresente um problema real do público em uma frase.\nProva: demonstre em contexto coerente com a experiência do Profile.\nVeredito: compare benefício, limitação e custo sem promessa falsa.\nCTA: ${profile.dna.mainCTA}`,[profile]);
  const copy=async()=>{await navigator.clipboard.writeText(kit);setCopied(true);window.setTimeout(()=>setCopied(false),2000);};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div className="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-[#272733] bg-[#111115]"><div className="flex items-center justify-between border-b border-[#24242c] px-5 py-4"><div className="flex items-center gap-2"><BriefcaseBusiness className="w-4 h-4 text-brand-400"/><div><h2 className="font-bold text-white">Kit profissional — {profile.name}</h2><p className="text-xs text-zinc-500">Posicionamento, direção editorial e roteiro-base derivados do DNA salvo.</p></div></div><button onClick={onClose} aria-label="Fechar kit profissional" className="p-2 text-zinc-500 hover:text-white"><X className="w-4 h-4"/></button></div><div className="overflow-y-auto p-5"><pre className="whitespace-pre-wrap rounded-xl border border-[#252530] bg-[#0b0b0f] p-4 font-sans text-xs leading-6 text-zinc-300">{kit}</pre></div><div className="flex justify-end gap-2 border-t border-[#24242c] px-5 py-4"><button onClick={onClose} className="px-4 py-2 text-xs font-semibold text-zinc-400">Fechar</button><button onClick={copy} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-2.5 text-xs font-bold text-white">{copied?<CheckCheck className="w-4 h-4"/>:<Copy className="w-4 h-4"/>}{copied?'Kit copiado':'Copiar kit completo'}</button></div></div></div>;
}
