'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, ExternalLink, Loader2, LockKeyhole, Plus, Send, ShieldCheck } from 'lucide-react';

type Account = {id:string;platform:string;display_name:string;handle?:string;avatar_url?:string;status:string};
type Health = { configuration: Record<string,{ready:boolean}>; cloud: { accounts?: Account[] } };
const NETWORKS = [
  {id:'instagram',name:'Instagram',icon:'📸',description:'Conecte perfis profissionais e páginas do Instagram.',connect:'/api/social/oauth/meta'},
  {id:'tiktok',name:'TikTok',icon:'🎵',description:'Conecte contas de criador autorizadas para publicação.',connect:'/api/social/oauth/tiktok'},
  {id:'shopee',name:'Shopee',icon:'🛍️',description:'Conecte sua conta quando a publicação oficial estiver disponível.'},
] as const;

export default function SocialNetworksPage(){
  const [health,setHealth]=useState<Health|null>(null),[notice,setNotice]=useState('');
  useEffect(()=>{void fetch('/api/social/health',{cache:'no-store'}).then(r=>r.json()).then(setHealth)},[]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('tiktok_connected'))setNotice('TikTok autorizado com sucesso. A conta já pode ser usada no Direct Post.');const error=params.get('tiktok_error');if(error){const messages:Record<string,string>={not_configured:'A integração TikTok ainda precisa das credenciais do aplicativo.',access_denied:'A autorização foi cancelada no TikTok.',missing_code:'O TikTok não retornou o código de autorização.',invalid_state:'A validação de segurança expirou. Tente conectar novamente.',token_exchange_failed:'Não foi possível concluir a autorização do TikTok.',missing_required_scope:'A conta não autorizou todas as permissões necessárias.'};setNotice(messages[error]||'Não foi possível conectar o TikTok.');}},[]);
  return <div className="mx-auto max-w-[1200px] space-y-6 p-4 sm:p-6 xl:p-8">
    <header><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-brand-300"><ShieldCheck className="h-4 w-4"/>Conexões seguras</div><h1 className="mt-2 text-2xl font-bold text-white">Conectar redes sociais</h1><p className="mt-1 max-w-2xl text-xs leading-5 text-zinc-400">Escolha uma rede, entre na tela oficial dela e autorize o PD. Sua senha nunca é exibida nem armazenada pelo sistema.</p></header>
    {notice&&<div className="rounded-xl border border-brand-400/20 bg-brand-400/5 px-4 py-3 text-xs text-brand-200">{notice}</div>}
    {!health?<div className="flex justify-center py-20"><Loader2 className="h-6 w-6 animate-spin text-brand-400"/></div>:<section className="grid gap-4 lg:grid-cols-3">{NETWORKS.map(net=>{const accounts=health.cloud.accounts?.filter(a=>a.platform===net.id)||[];const ready=net.id==='instagram'?health.configuration.instagram?.ready:net.id==='tiktok'?health.configuration.tiktok?.ready:false;return <article key={net.id} className="flex min-h-[300px] flex-col rounded-2xl border border-white/8 bg-gradient-to-b from-[#15151b] to-[#101014] p-5 shadow-subtle"><div className="flex items-center justify-between"><span className="text-3xl">{net.icon}</span><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold ${accounts.length?'bg-emerald-400/10 text-emerald-300':'bg-white/5 text-zinc-500'}`}>{accounts.length?`${accounts.length} conectada${accounts.length===1?'':'s'}`:'Não conectado'}</span></div><h2 className="mt-4 text-base font-bold text-white">{net.name}</h2><p className="mt-1 text-[11px] leading-5 text-zinc-500">{net.description}</p><div className="mt-4 flex-1 space-y-2">{accounts.map(account=><div key={account.id} className="flex items-center gap-3 rounded-xl border border-emerald-400/15 bg-emerald-400/5 p-3">{account.avatar_url?<img src={account.avatar_url} alt="" className="h-8 w-8 rounded-full object-cover"/>:<CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400"/>}<div className="min-w-0"><div className="truncate text-xs font-semibold text-zinc-200">{account.display_name}</div><div className="truncate text-[9px] text-emerald-400">Conectado</div></div></div>)}</div>{net.id==='tiktok'&&accounts.length>0&&<Link href="/publicar-tiktok" className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-cyan-400/20 bg-cyan-400/10 py-2.5 text-xs font-bold text-cyan-200"><Send className="h-4 w-4"/>Publicar vídeo</Link>}{'connect' in net&&net.connect?<a href={net.connect} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-600 py-3 text-xs font-bold text-white hover:bg-brand-500"><Plus className="h-4 w-4"/>{accounts.length?'Conectar outra conta':`Entrar com ${net.name}`}<ExternalLink className="h-3.5 w-3.5 opacity-60"/></a>:<div className="mt-4 flex items-center gap-2 rounded-xl border border-white/8 bg-white/[.03] p-3 text-[10px] leading-4 text-zinc-500"><LockKeyhole className="h-4 w-4 shrink-0"/>Conexão oficial ainda não liberada pela plataforma.</div>}{'connect' in net&&net.connect&&!ready&&<p className="mt-2 text-center text-[9px] text-amber-300/80">Ativação da integração pendente pelo administrador do PD.</p>}</article>})}</section>}
    <div className="rounded-2xl border border-blue-400/15 bg-blue-400/5 p-4 text-[10px] leading-5 text-zinc-400"><strong className="text-blue-200">Como funciona:</strong> ao clicar em conectar, você sai por alguns instantes para a página oficial da rede, faz login e escolhe quais contas deseja autorizar. Depois retorna automaticamente ao PD.</div>
  </div>;
}
