create extension if not exists pgcrypto;
create table if not exists teams (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table if not exists team_members (team_id uuid references teams(id) on delete cascade, user_id uuid not null, role text not null check (role in ('owner','admin','editor','viewer')), primary key(team_id,user_id));
create table if not exists social_accounts (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id) on delete cascade, profile_id text, platform text not null, platform_account_id text not null, display_name text not null, handle text, access_token_ciphertext text not null, refresh_token_ciphertext text, token_expires_at timestamptz, status text not null default 'connected', created_at timestamptz not null default now(), unique(team_id,platform,platform_account_id));
create table if not exists social_posts (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id) on delete cascade, profile_id text not null, media_id text not null, platform text not null, scheduled_at timestamptz not null, caption text not null default '', settings jsonb not null default '{}', status text not null default 'draft', dedupe_key text not null, attempts int not null default 0, next_attempt_at timestamptz, remote_id text, permalink text, last_error text, created_at timestamptz not null default now(), unique(team_id,dedupe_key));
create table if not exists social_post_targets (post_id uuid references social_posts(id) on delete cascade, account_id uuid references social_accounts(id) on delete cascade, status text not null default 'queued', remote_id text, permalink text, last_error text, primary key(post_id,account_id));
create table if not exists social_audit_log (id bigserial primary key, team_id uuid not null references teams(id) on delete cascade, actor_user_id uuid, action text not null, entity_type text not null, entity_id text not null, details jsonb not null default '{}', created_at timestamptz not null default now());
create index if not exists social_due_posts on social_posts(status,scheduled_at,next_attempt_at);
alter table teams enable row level security; alter table team_members enable row level security; alter table social_accounts enable row level security; alter table social_posts enable row level security; alter table social_post_targets enable row level security; alter table social_audit_log enable row level security;
