import Link from 'next/link';
import { BookOpen, Cable, ShoppingBag, UserRound, Video } from 'lucide-react';

const guides=[
  {icon:UserRound,title:'1. Crie um Profile profissional',text:'Escolha um arquétipo no Dark Radar ou informe profissão, experiência, personalidade e tom no criador.',href:'/profiles?create=1',cta:'Criar Profile'},
  {icon:ShoppingBag,title:'2. Importe um produto',text:'Cole o link afiliado. O PD preserva os parâmetros e recomenda três personagens contextualizados.',href:'/afiliado',cta:'Analisar produto'},
  {icon:Cable,title:'3. Configure provedores',text:'O upload local já funciona. Geração real permanece bloqueada até texto, imagem, voz e vídeo responderem ao teste.',href:'/integracoes',cta:'Ver integrações'},
  {icon:Video,title:'4. Valide antes de escalar',text:'Faça o teste rápido de 5 segundos, revise o resultado real e só depois abra a geração em massa.',href:'/?newGeneration=1',cta:'Abrir gerador'},
];
export default function HelpPage(){return <div className="mx-auto max-w-5xl p-5 sm:p-8"><div className="flex items-center gap-3"><BookOpen className="w-6 h-6 text-brand-400"/><div><h1 className="text-2xl font-bold text-white">Central de ajuda</h1><p className="text-sm text-zinc-400">Fluxo recomendado para trabalhar sem resultados simulados.</p></div></div><div className="mt-7 grid sm:grid-cols-2 gap-4">{guides.map(({icon:Icon,...guide})=><article key={guide.title} className="rounded-2xl border border-[#25252d] bg-[#111116] p-5"><Icon className="w-5 h-5 text-brand-400"/><h2 className="mt-3 font-bold text-white">{guide.title}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{guide.text}</p><Link href={guide.href} className="mt-4 inline-flex rounded-lg bg-brand-600 px-4 py-2 text-xs font-bold text-white">{guide.cta}</Link></article>)}</div><div className="mt-6 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><h2 className="font-semibold text-white">Antes de gerar</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Adicione uma referência visual própria ou licenciada, confirme os dados do produto e teste as integrações. O PD não apresenta mídia de demonstração como produção real.</p></div></div>}
